# Generated by Django 3.2.12 on 2022-06-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assigntrip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('driversname', models.CharField(max_length=250)),
                ('travel_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'assigntrip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bookingtickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('froms', models.CharField(max_length=200)),
                ('destinations', models.CharField(max_length=100)),
                ('via', models.CharField(max_length=100)),
                ('ticket_no', models.IntegerField()),
                ('price', models.IntegerField()),
                ('busname', models.CharField(max_length=100)),
                ('busnumber', models.CharField(max_length=100)),
                ('travel_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'bookingtickets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusesPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bookingtickets_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'buses_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driversname', models.CharField(max_length=250)),
                ('nida', models.TextField()),
                ('licenseno', models.CharField(max_length=50)),
                ('levels', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('message', models.TextField()),
                ('status', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('companyname', models.CharField(max_length=250)),
                ('user_type', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('logo', models.TextField()),
                ('officelocation', models.TextField()),
                ('phone', models.IntegerField()),
                ('workingtime', models.TimeField()),
                ('passwords', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'operators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('via', models.CharField(max_length=250)),
                ('froms', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'routes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_no', models.IntegerField()),
                ('occupant_first_name', models.CharField(max_length=255)),
                ('occupant_second_name', models.CharField(max_length=255)),
                ('occupant_email', models.CharField(max_length=255)),
                ('purchase_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'seat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('busname', models.CharField(max_length=250)),
                ('companyname', models.CharField(max_length=250)),
                ('busnumber', models.TextField()),
                ('busclass', models.CharField(max_length=250)),
                ('insuranceno', models.TextField()),
                ('logo', models.TextField()),
                ('booked_seats', models.ManyToManyField(blank=b'I01\n', to='bus_catalog.Seat')),
            ],
            options={
                'db_table': 'buses',
                'managed': True,
            },
        ),
    ]
