# Generated by Django 3.2.12 on 2022-06-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.CharField(max_length=250, unique=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
